CREATE USER MATSIUK IDENTIFIED BY YAHENI;

grant CREATE SESSION, ALTER SESSION, CREATE DATABASE LINK, -
  CREATE MATERIALIZED VIEW, CREATE PROCEDURE, CREATE PUBLIC SYNONYM, -
  CREATE ROLE, CREATE SEQUENCE, CREATE SYNONYM, CREATE TABLE, - 
  CREATE TRIGGER, CREATE TYPE, CREATE VIEW, UNLIMITED TABLESPACE -
  to MATSIUK; 

  CREATE TABLE IF NOT EXISTS "MATSIUK"."NEWS" 
   (	"ID" NUMBER, 
	"TITLE" VARCHAR2(50 BYTE), 
	"DESCRIPTION" VARCHAR2(200 BYTE), 
	"FULL_TEXT" VARCHAR2(4000 BYTE), 
	"CREATION_DATE" TIMESTAMP (6), 
	"MODIFICATION_DATE" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into MATSIUK.NEWS
SET DEFINE OFF;

  CREATE UNIQUE INDEX "MATSIUK"."NEWS_PK" ON "MATSIUK"."NEWS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
  
    ALTER TABLE "MATSIUK"."NEWS" MODIFY ("MODIFICATION_DATE" NOT NULL ENABLE);
  ALTER TABLE "MATSIUK"."NEWS" MODIFY ("CREATION_DATE" NOT NULL ENABLE);
  ALTER TABLE "MATSIUK"."NEWS" MODIFY ("FULL_TEXT" NOT NULL ENABLE);
  ALTER TABLE "MATSIUK"."NEWS" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "MATSIUK"."NEWS" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "MATSIUK"."NEWS" ADD CONSTRAINT "NEWS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "MATSIUK"."NEWS" MODIFY ("ID" NOT NULL ENABLE);

  CREATE TABLE IF NOT EXISTS "MATSIUK"."AUTHORS" 
   (	"ID" NUMBER, 
	"NAME" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into MATSIUK.AUTHORS
SET DEFINE OFF;

  CREATE UNIQUE INDEX "MATSIUK"."AUTHORS_PK" ON "MATSIUK"."AUTHORS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
  
    ALTER TABLE "MATSIUK"."AUTHORS" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "MATSIUK"."AUTHORS" ADD CONSTRAINT "AUTHORS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "MATSIUK"."AUTHORS" MODIFY ("ID" NOT NULL ENABLE);

  CREATE TABLE IF NOT EXISTS "MATSIUK"."COMMENTS" 
   (	"ID" NUMBER, 
	"TEXT" VARCHAR2(300 BYTE), 
	"CREATION_DATE" TIMESTAMP (6), 
	"ID_NEWS" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into MATSIUK.COMMENTS
SET DEFINE OFF;

  CREATE UNIQUE INDEX "MATSIUK"."SYS_C007110" ON "MATSIUK"."COMMENTS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
  
    ALTER TABLE "MATSIUK"."COMMENTS" MODIFY ("CREATION_DATE" NOT NULL ENABLE);
  ALTER TABLE "MATSIUK"."COMMENTS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "MATSIUK"."COMMENTS" MODIFY ("ID_NEWS" NOT NULL ENABLE);
  ALTER TABLE "MATSIUK"."COMMENTS" MODIFY ("TEXT" NOT NULL ENABLE);
  ALTER TABLE "MATSIUK"."COMMENTS" MODIFY ("ID" NOT NULL ENABLE);
  
    ALTER TABLE "MATSIUK"."COMMENTS" ADD CONSTRAINT "COMMENTS_FOREIGN" FOREIGN KEY ("ID_NEWS")
	  REFERENCES "MATSIUK"."NEWS" ("ID") ON DELETE CASCADE ENABLE;

  CREATE TABLE IF NOT EXISTS "MATSIUK"."TAG" 
   (	"NAME" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into MATSIUK.TAG
SET DEFINE OFF;

  CREATE UNIQUE INDEX "MATSIUK"."TAG_PK" ON "MATSIUK"."TAG" ("NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
  
    ALTER TABLE "MATSIUK"."TAG" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "MATSIUK"."TAG" ADD CONSTRAINT "TAG_PK" PRIMARY KEY ("NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  
    CREATE TABLE IF NOT EXISTS "MATSIUK"."NEWS_AUTHORS" 
   (	"NEWS_ID" NUMBER, 
	"AUTHOR_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into MATSIUK.NEWS_AUTHORS
SET DEFINE OFF;

  ALTER TABLE "MATSIUK"."NEWS_AUTHORS" MODIFY ("AUTHOR_ID" NOT NULL ENABLE);
  ALTER TABLE "MATSIUK"."NEWS_AUTHORS" MODIFY ("NEWS_ID" NOT NULL ENABLE);
  
    ALTER TABLE "MATSIUK"."NEWS_AUTHORS" ADD CONSTRAINT "NEWS_AUTHORS" FOREIGN KEY ("NEWS_ID")
	  REFERENCES "MATSIUK"."NEWS" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "MATSIUK"."NEWS_AUTHORS" ADD CONSTRAINT "NEWS_AUTHORS_FOREIGN" FOREIGN KEY ("AUTHOR_ID")
	  REFERENCES "MATSIUK"."AUTHORS" ("ID") ON DELETE CASCADE ENABLE;
	  
	    CREATE TABLE IF NOT EXISTS "MATSIUK"."NEWS_TAG" 
   (	"NEWS_ID" NUMBER, 
	"TAG" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into MATSIUK.NEWS_TAG
SET DEFINE OFF;

  ALTER TABLE "MATSIUK"."NEWS_TAG" MODIFY ("TAG" NOT NULL ENABLE);
  ALTER TABLE "MATSIUK"."NEWS_TAG" MODIFY ("NEWS_ID" NOT NULL ENABLE);
  
    ALTER TABLE "MATSIUK"."NEWS_TAG" ADD CONSTRAINT "NEWS_TAG_FOREING" FOREIGN KEY ("NEWS_ID")
	  REFERENCES "MATSIUK"."NEWS" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "MATSIUK"."NEWS_TAG" ADD CONSTRAINT "TAG_FK" FOREIGN KEY ("TAG")
	  REFERENCES "MATSIUK"."TAG" ("NAME") ON DELETE CASCADE ENABLE;
	 
  CREATE SEQUENCE  "MATSIUK"."NEWS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 10680 CACHE 20 NOORDER  NOCYCLE ;
     CREATE SEQUENCE  "MATSIUK"."AUTHOR_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 182 CACHE 20 NOORDER  NOCYCLE ;
        CREATE SEQUENCE  "MATSIUK"."COMMENT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 93731 CACHE 20 NOORDER  NOCYCLE ;
           CREATE SEQUENCE  "MATSIUK"."TAG_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE ;
           
     
  