--------------------------------------------------------
--  File created - Monday-November-09-2015   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table NEWS
--------------------------------------------------------

CREATE USER MATSIUK IDENTIFIED BY YAHENI;

grant CREATE SESSION, ALTER SESSION, CREATE DATABASE LINK, -
  CREATE MATERIALIZED VIEW, CREATE PROCEDURE, CREATE PUBLIC SYNONYM, -
  CREATE ROLE, CREATE SEQUENCE, CREATE SYNONYM, CREATE TABLE, - 
  CREATE TRIGGER, CREATE TYPE, CREATE VIEW, UNLIMITED TABLESPACE -
  to MATSIUK;

  CREATE TABLE IF NOT EXISTS "MATSIUK"."NEWS" 
   (	"ID" NUMBER, 
	"TITLE" VARCHAR2(50 BYTE), 
	"DESCRIPTION" VARCHAR2(200 BYTE), 
	"FULL_TEXT" VARCHAR2(4000 BYTE), 
	"CREATION_DATE" TIMESTAMP (6), 
	"MODIFICATION_DATE" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into MATSIUK.NEWS
SET DEFINE OFF;

CREATE SEQUENCE  "MATSIUK"."NEWS_SEQ1"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 201 CACHE 20 NOORDER  NOCYCLE ;